"""Add UUID column to accounts table

Revision ID: 19a9da6dc9af
Revises: 356326cf6f55
Create Date: 2025-11-17 20:24:21.550823

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import uuid


# revision identifiers, used by Alembic.
revision: str = '19a9da6dc9af'
down_revision: Union[str, None] = '356326cf6f55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add UUID column as nullable first
    op.add_column('accounts', sa.Column('uuid', sa.UUID(), nullable=True))
    
    # Generate UUIDs for existing accounts
    connection = op.get_bind()
    result = connection.execute(sa.text("SELECT id FROM accounts"))
    for row in result:
        connection.execute(
            sa.text("UPDATE accounts SET uuid = :uuid_val WHERE id = :id_val"),
            {"uuid_val": str(uuid.uuid4()), "id_val": row.id}
        )
    
    # Make UUID column non-nullable and add unique constraint
    op.alter_column('accounts', 'uuid', nullable=False)
    op.create_unique_constraint(None, 'accounts', ['uuid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'accounts', type_='unique')
    op.drop_column('accounts', 'uuid')
    # ### end Alembic commands ###
